### ISSUE TITLE
[Issue] Conflict with ViaFabricPlus

### ISSUE THREAD

**Issue by renceron55th** [AnOpenSauceDev/Methane-mod#62]
[crash-2023-10-27_18.25.41.1268-quilt_loader.txt](https://github.com/AnOpenSauceDev/Methane-mod/files/13190981/crash-2023-10-27_18.25.41.1268-quilt_loader.txt)

As I understand from this crash blog, it is written here about incompatibility with these two mods.

at the time of writing, I was using the latest version of both mods: Methane 2.5.0 , ViaFabricPlus 2.9.5

**Comment by AnOpenSauceDev** [comment]
Reading this log, it looks like it might have something to do with the toast removal, but it also might be a bug with FastLoad as well.

**Comment by AnOpenSauceDev** [comment]
Could not replicate on 2.5.0 with the following modlist:
- Methane 2.5.0
- Minecraft 1.20.2
- Mod Menu 8.0.0
- ViaFabricPlus 2.9.5 (works for me set as 1.20.x, 1.17.x, 1.8.x)

**Comment by AnOpenSauceDev** [comment]
Unfortunately, this is a bug with FastLoad and possibly one of your other mods. I don't see how else Methane could conflict with this. Also, I wouldn't recommend mixing and matching 1.20.1 and 1.20.2 mods, because some calls will crash the game if they don't exist/have changed significantly on 1.20.2. Feel free to open this issue again if you do find any issues with ViaFabric+

**Comment by renceron55th** [comment]
Sorry, I didn't misunderstand the error. Thanks for the help
