### ISSUE TITLE
A question and possible issue. 1.20.4

### ISSUE THREAD

**Issue by DatrixTHLK2024** [AnOpenSauceDev/Methane-mod#91]
Is it normal that mobs (like skeletons and zombies) don't burn during the day time? I have enabled the legacy lighting option to have mobs spawn normally, but none of the hostile mobs burn during the day time. They seem to spawn during the day time anyway if they are in the forest area. The FPS boost is great and all, but is there an option I can enable that can make mobs burn during the day

Minecraft: 1.20.4
Fabric:  0.15.7
Methane: 3.6.0

**Comment by AnOpenSauceDev** [comment]
Can't replicate, mobs burn correctly when exposed to the sun for me.

**Comment by DatrixTHLK2024** [comment]
Strange...thanks anyways...

**Comment by AnOpenSauceDev** [comment]
closing as being unable to replicate. (mobs also burned with the new lighting engine)

**Comment by DatrixTHLK2024** [comment]
I tried playing with your mod and a few other core mods that are needed to make Fabric work and only those mentioned below

Minecraft: 1.20.4
Fabric Loader: 0.15.7
Fabric API: 0.96.11
Cloth Config 13.0.121
Methane: 3.6.0

I still haven't seen any mobs burn in the daytime. Where is the options in your mod to enable that setting? Or do you not have that setting at all in your mod? You tell me you can't replicate it and I don't know why that is if it happens on my side of things. It can't be just my issue. I can't be the only one with weird issues like this. Explain to me what I'm doing wrong, please?

**Comment by AnOpenSauceDev** [comment]
Apologies, it turns out that mobs do burn in daylight once you've generated part of a world with methane OFF (meaning that lightStorage can see if a mob burns under cover or not based off the sky's brightness). I think this is from a pretty new optimization that I made for memory, so if you play with an older version of Methane before the new lighting engine this shouldn't happen.

Aside from that, there isn't really a fix i can suggest or make as I cannot work on updating Methane currently.

**Comment by AnOpenSauceDev** [comment]
There is a feature in the config called "Start with Methane On?" If you disable that, joining a world will have methane OFF by default.
